title: Red's blog on life. And Cats.
author: RedlightSparks 
email: redlight.sparks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  RedlightSparks' blog of awesomeness.
# social links
twitter_username: RedlightSparks
github_username:  RedlightSparks

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
